name: train

on:
#  schedule:
#    - cron: '0 2 * * *'  # каждый день в 2:00 UTC
  workflow_dispatch:      # кнопка Run workflow в UI

jobs:
  train:
    runs-on: self-hosted  # используем ваш runner, где есть доступ к продовому MLflow

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install mlflow

      - name: Train and log to MLflow
        env:
          MLFLOW_URI: http://localhost:5000  # ваш продовый MLflow на той же машине
        run: python train.py

      - name: Model quality gate
        run: python check_model.py